org.gradle.jvmargs=-Xms512m -Xmx2g -Dfile.encoding=UTF-8
org.gradle.warning.mode=all

# Java / Gradle
javaVersion=21
gradleVersion=9.4.0

# Version
appVersion=0.1.7

# Plugin versions
beryxRuntimePluginVersion=2.0.0
graalNativePluginVersion=0.11.1

# Test versions
junitVersion=4.13.2
hamcrestVersion=1.3

# Core libs
gdxVersion=1.14.0
aiVersion=1.8.2
artemisOdbVersion=2.3.0
fastutilVersion=8.5.18
